// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	model "github.com/cerfical/merchshop/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// AuthUser provides a mock function with given fields: _a0
func (_m *AuthService) AuthUser(_a0 model.UserCreds) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AuthUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(model.UserCreds) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(model.UserCreds) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(model.UserCreds) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_AuthUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthUser'
type AuthService_AuthUser_Call struct {
	*mock.Call
}

// AuthUser is a helper method to define mock.On call
//   - _a0 model.UserCreds
func (_e *AuthService_Expecter) AuthUser(_a0 interface{}) *AuthService_AuthUser_Call {
	return &AuthService_AuthUser_Call{Call: _e.mock.On("AuthUser", _a0)}
}

func (_c *AuthService_AuthUser_Call) Run(run func(_a0 model.UserCreds)) *AuthService_AuthUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.UserCreds))
	})
	return _c
}

func (_c *AuthService_AuthUser_Call) Return(_a0 string, _a1 error) *AuthService_AuthUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_AuthUser_Call) RunAndReturn(run func(model.UserCreds) (string, error)) *AuthService_AuthUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
