// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordHasher is an autogenerated mock type for the PasswordHasher type
type PasswordHasher struct {
	mock.Mock
}

type PasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordHasher) EXPECT() *PasswordHasher_Expecter {
	return &PasswordHasher_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function with given fields: passwd
func (_m *PasswordHasher) HashPassword(passwd string) ([]byte, error) {
	ret := _m.Called(passwd)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(passwd)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(passwd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(passwd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordHasher_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type PasswordHasher_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - passwd string
func (_e *PasswordHasher_Expecter) HashPassword(passwd interface{}) *PasswordHasher_HashPassword_Call {
	return &PasswordHasher_HashPassword_Call{Call: _e.mock.On("HashPassword", passwd)}
}

func (_c *PasswordHasher_HashPassword_Call) Run(run func(passwd string)) *PasswordHasher_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PasswordHasher_HashPassword_Call) Return(_a0 []byte, _a1 error) *PasswordHasher_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PasswordHasher_HashPassword_Call) RunAndReturn(run func(string) ([]byte, error)) *PasswordHasher_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function with given fields: passwd, passwdHash
func (_m *PasswordHasher) VerifyPassword(passwd string, passwdHash []byte) (bool, error) {
	ret := _m.Called(passwd, passwdHash)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []byte) (bool, error)); ok {
		return rf(passwd, passwdHash)
	}
	if rf, ok := ret.Get(0).(func(string, []byte) bool); ok {
		r0 = rf(passwd, passwdHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = rf(passwd, passwdHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordHasher_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type PasswordHasher_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - passwd string
//   - passwdHash []byte
func (_e *PasswordHasher_Expecter) VerifyPassword(passwd interface{}, passwdHash interface{}) *PasswordHasher_VerifyPassword_Call {
	return &PasswordHasher_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", passwd, passwdHash)}
}

func (_c *PasswordHasher_VerifyPassword_Call) Run(run func(passwd string, passwdHash []byte)) *PasswordHasher_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *PasswordHasher_VerifyPassword_Call) Return(_a0 bool, _a1 error) *PasswordHasher_VerifyPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PasswordHasher_VerifyPassword_Call) RunAndReturn(run func(string, []byte) (bool, error)) *PasswordHasher_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewPasswordHasher creates a new instance of PasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHasher {
	mock := &PasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
