// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	model "github.com/cerfical/merchshop/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// PutUser provides a mock function with given fields: _a0
func (_m *UserRepo) PutUser(_a0 *model.User) (*model.User, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for PutUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.User) (*model.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*model.User) *model.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepo_PutUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutUser'
type UserRepo_PutUser_Call struct {
	*mock.Call
}

// PutUser is a helper method to define mock.On call
//   - _a0 *model.User
func (_e *UserRepo_Expecter) PutUser(_a0 interface{}) *UserRepo_PutUser_Call {
	return &UserRepo_PutUser_Call{Call: _e.mock.On("PutUser", _a0)}
}

func (_c *UserRepo_PutUser_Call) Run(run func(_a0 *model.User)) *UserRepo_PutUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.User))
	})
	return _c
}

func (_c *UserRepo_PutUser_Call) Return(_a0 *model.User, _a1 error) *UserRepo_PutUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepo_PutUser_Call) RunAndReturn(run func(*model.User) (*model.User, error)) *UserRepo_PutUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
