with-expecter: true
packages:
  github.com/cerfical/merchshop/internal/service/auth:
    interfaces:
      PasswordHasher:
      TokenAuth:
      AuthService:
  github.com/cerfical/merchshop/internal/service/coins:
    interfaces:
      CoinService:
  github.com/cerfical/merchshop/internal/service/model:
    interfaces:
      UserRepo:

outpkg: "mocks"
dir: "internal/mocks"
mockname: "{{ .InterfaceName }}"
filename: "{{ .InterfaceName | snakecase }}.go"
