with-expecter: true
packages:
  github.com/cerfical/merchshop/internal/domain/auth:
    interfaces:
      PasswordHasher:
      TokenGen:
      UserRepo:

outpkg: "mocks"
dir: "internal/mocks"
mockname: "{{ .InterfaceName }}"
filename: "{{ .InterfaceName | snakecase }}.go"
