with-expecter: true
packages:
  github.com/cerfical/merchshop/internal/service/auth:
    interfaces:
      PasswordHasher:
      TokenAuth:
  github.com/cerfical/merchshop/internal/service/repo:
    interfaces:
      UserRepo:

outpkg: "mocks"
dir: "internal/mocks"
mockname: "{{ .InterfaceName }}"
filename: "{{ .InterfaceName | snakecase }}.go"
