with-expecter: true
packages:
  github.com/cerfical/merchshop/internal/domain/services:
    interfaces:
      PasswordHasher:
      TokenGen:
      AuthService:
      CoinService:
  github.com/cerfical/merchshop/internal/domain/repo:
    interfaces:
      UserRepo:

outpkg: "mocks"
dir: "internal/mocks"
mockname: "{{ .InterfaceName }}"
filename: "{{ .InterfaceName | snakecase }}.go"
